apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics
  namespace: metrics
  labels:
    app: &app metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: *app
  template:
    metadata:
      labels:
        app: *app
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "80"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: nginx
        image: bitnami/nginx:latest
        ports:
        - containerPort: 80
          name: metrics
      nodeSelector:
        kubernetes.io/hostname: worker-node-1.test.local
      resources:
        requests:
          cpu: 50m
          memory: 100Mi
        limits:
          cpu: 100m
          memory: 200Mi