apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: metrics-service-monitor
  namespace: metrics 
  labels:
    app: &app metrics
    team: backend
spec:
  selector:
    matchLabels:
      app: *app
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics