apiVersion: v1
kind: Service
metadata:
  name: metrics-service
  namespace: metrics
  labels:
    app: &app metrics
spec:
  type: NodePort
  selector:
    app: *app
  ports:
    - protocol: TCP
      port: 80
      targetPort: metrics
      nodePort: 30008
      prefix: /metrics
