apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami
  namespace: whoami
spec:
  replicas: 1
  selector:
    matchLabels:
      version: "1.0"
  template:
    metadata:
      labels:
        version: "1.0"
    spec:
      containers:
      - name: whoami-container
        image: traefik/whoami:v1.8.0 # Use a specific image version
        ports:
        - name: web
          containerPort: 80
        resources:
          requests:
            cpu: 40m
            memory: 20Mi
          limits:
            cpu: 90m
            memory: 90Mi
        livenessProbe:
          httpGet:
            path: /health # Use the health endpoint
            port: web
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health # Use the health endpoint
            port: web
          initialDelaySeconds: 5
          periodSeconds: 10
      serviceAccountName: whoami-sa  
      priorityClassName: high-priority-nonpreempting
