apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - namespace.yaml
  - PriorityClass.yaml
  - service_account.yaml
  - role_binding.yaml
  - role.yaml

# Добавление общих меток
commonLabels:
  app: whoami