apiVersion: v1
kind: Service
metadata:
  name: whoami-service
  namespace: whoami
spec:
  type: NodePort
  selector:
    version: "1.0"
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007
