apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Подключаем базовую конфигурацию
resources:
  - ../../base

# Добавление префикса
namePrefix: prod

# Патчи (изменения)
patchesStrategicMerge:
  - replica.yaml