apiVersion: v1
kind: Service
metadata:
  name: whoami-service
  namespace: whoami
spec:
  type: NodePort
  selector:
    app: whoami
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007
root@control-plane-1:/etc/manifest/whoami# cat deployment.yaml 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami
  namespace: whoami
  labels:
    app: whoami
spec:
  replicas: 3
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
      - name: whoami-container
        image: traefik/whoami:v1.8.0 # Use a specific image version
        ports:
        - name: web
          containerPort: 80
        livenessProbe:
          httpGet:
            path: /health # Use the health endpoint
            port: web
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health # Use the health endpoint
            port: web
          initialDelaySeconds: 5
          periodSeconds: 10
