apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-metrics-config
data:
  nginx.conf: |
    events {
        worker_connections 1024;
    }
    http {
        server {
            listen 80;
            location /nginx_status {
                stub_status on;
                allow all;
            }
            location / {
                # Simple response for demonstration
                return 200 'Hello from Airat Fatikhov';
            }
        }
    }