apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: nginx
  labels:
    app: &app nginx
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "9113"
spec:
  selector:
    app: *app
  ports:
    - name: nginx
      port: 80
      targetPort: 80
      nodePort: 30008
    - name: metrics
      port: 9113
      targetPort: 9113
      nodePort: 30009
