apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami
  namespace: whoami
  labels:
    app: &app whoami
spec:
  replicas: 1
  selector:
    matchLabels:
      app: *app
  template:
    metadata:
      labels:
        app: *app
    spec:
      nodeSelector:
        node-role.kubernetes.io/worker: "true"
      containers:
      - name: whoami-container
        image: traefik/whoami:v1.8.0 # Use a specific image version
        ports:
        - name: web
          containerPort: 80
        resources:
          requests:
            cpu: 50m
            memory: 20Mi
          limits:
            cpu: 100m
            memory: 100Mi
        livenessProbe:
          httpGet:
            path: /health # Use the health endpoint
            port: web
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health # Use the health endpoint
            port: web
          initialDelaySeconds: 5
          periodSeconds: 10
