apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: metrics-service-monitor
  namespace: nginx
  labels:
    app: &app nginx
    team: backend
spec:
  selector:
    matchLabels:
      app: *app
  namespaceSelector:
    matchNames:
      - nginx
  endpoints:
  - port: metrics
    interval: 30s