apiVersion: v1
kind: Service
metadata:
  name: nginx-metrics-service
  namespace: whoami
  labels:
    app: &app nginx
spec:
  type: NodePort
  selector:
    app: *app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30008
